fetch("https://www.opposhop.cn/cn/oapi/users/web/address", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/x-www-form-urlencoded",
    "encryption": "SgNgGANI/R9aTEtKpHMFS0g5SvpvUdbGg+OSJMfUuXL22UgbOZ4KL+e7rO2Kp2zvSjml/EBeJHnRR/j+OgoeHw==",
    "notoast": "1",
    "reqfilter": "true",
    "s_channel": "h5_web",
    "sec-ch-ua": "\"Google Chrome\";v=\"143\", \"Chromium\";v=\"143\", \"Not A(Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "source_type": "504",
    "uc": "direct",
    "um": "003880",
    "us": "fenleiye",
    "ut": "rengong",
    "utm_campaign": "direct",
    "utm_medium": "direct",
    "utm_source": "direct",
    "utm_term": "direct"
  },
  "referrer": "https://www.opposhop.cn/cn/web/user/addresses",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "id=29786653&receiver=fR%2Bteu9PUxI85VhphnlvjA%3D%3D&mobile=6vahteBqAbLmNiFihU26Fw%3D%3D&address=DWNRnMGGZ4%2Fhg3sJ9e8w8w%3D%3D&isDefault=1&provinceId=32&cityId=398&districtId=3380&townId=45347",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
